### ISSUE TITLE
script issue

### ISSUE THREAD

**Issue by coldvisionz** [Deytron/lutris-art-downloader#2]
Traceback (most recent call last):
  File "/home/echo/lutris-art-downloader/main.py", line 130, in <module>
    main()
  File "/home/echo/lutris-art-downloader/main.py", line 23, in main
    GetGamesList(co)
  File "/home/echo/lutris-art-downloader/main.py", line 124, in GetGamesList
    DownloadCover(title)
  File "/home/echo/lutris-art-downloader/main.py", line 113, in DownloadCover
    with open(covpath + name + '.jpg', 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/echo/.cache/lutris/banners/the-elder-scrolls-5-skyrim.jpg'

**Comment by coldvisionz** [comment]
nevermind, fixed by creating 'banners' directory in lutris dir
